### ISSUE TITLE
Adjust decimal places of "secondary_info"

### ISSUE THREAD

**Issue by sebstef1412** [JonahKr/power-distribution-card#144] opened 2023-05-20 07:08 UTC
Hello it would be nice if you could adjust the decimal places of "secondary_info". 

![Screenshot 2023-05-20 090700](https://github.com/JonahKr/power-distribution-card/assets/95748890/d6a0f55f-99a7-4e86-b685-78da1c207ee3)

**Comment by JonahKr** [comment] 2023-05-20 09:36
Duplicate of #135 because seconardy_info is handled a san entity

**Closed by JonahKr** 2023-05-20 09:36 UTC
