### ISSUE TITLE
save values in autarky & ratio

### ISSUE THREAD

**Issue by mxwi** [JonahKr/power-distribution-card#55] opened 2021-02-19 07:23 UTC
Hi,

thanks for you card. I really like it!

Is it possible to save the 'autarky' & 'ratio' values in a sensor? I want to put them in my influxdb.

Thanks!

**Comment by JonahKr** [comment] 2021-02-19 08:31
Duplicate of #54

**Comment by JonahKr** [comment] 2021-02-19 08:36
Hi there 👋 ,

I sadly have to inform you that this simply isn't possible for me atm. I don't know if there are endpoints available to custom cards which allow this kind of support but I doubt it tbh. Since you are the second person to ask, i will get in contect with the frontend devs and look at the available options.
Take care and stay safe !

Jonah

**Comment by JonahKr** [comment] 2021-02-23 10:44
https://discord.com/channels/330944238910963714/351047592588869643/813721902635548693
Sadly not possible.

**Closed by JonahKr** 2021-02-23 10:44 UTC
Labels: duplicate
