### ISSUE TITLE
Tap Action

### ISSUE THREAD

**Issue by matthewjporter** [JonahKr/power-distribution-card#65] opened 2021-04-11 15:39 UTC
Is is possible to add tap_action to an entity?

Example, I have two batteries and every now and again when I have excess solar or no need for both batteries to discharge I find that one is discarhging and the other is charging from the other

A tap_action would allow me to run a service to trigger an automation that will disable one from discharging

What happens now is the default get_info action

Cheers

**Comment by JonahKr** [comment] 2021-04-11 15:46
Hey there 👋 
There is already a issue for this one so i will reference it and close this one.

Duplicate of #62 

Take care and stay safe!

Jonah

**Comment by JonahKr** [comment] 2021-04-11 15:46
Duplicate of #62

**Closed by JonahKr** 2021-04-11 15:46 UTC

**Comment by matthewjporter** [comment] 2021-04-11 16:02
Cheers
